# fly.toml file generated for rough-glitter-5665 on 2022-05-03T13:26:14Z

app = "rough-glitter-5665"

kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
  CRYSTALLIZE_TENANT_IDENTIFIER = "tsvetochki-test"
  NODE_ENV = "production"
  SERVICE_API_URL = "https://remix-service-api.vercel.app/api/graphql"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 3000
  processes = ["app"]
  protocol = "tcp"
  script_checks = []

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
